/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 48
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 22
#define ALIAS_COUNT 0
#define TOKEN_COUNT 10
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_name_section = 1,
  sym_stop_section = 2,
  sym_comment = 3,
  aux_sym_narrative_token1 = 4,
  aux_sym_narrative_token2 = 5,
  anon_sym_u2014 = 6,
  aux_sym__open_dialog_token1 = 7,
  aux_sym__open_narrative_token1 = 8,
  anon_sym_LF = 9,
  sym_document = 10,
  sym_section = 11,
  sym_narrative = 12,
  sym_dialog = 13,
  sym__open_dialog = 14,
  sym__end_dialog = 15,
  sym__open_narrative = 16,
  sym__end_narrative = 17,
  sym__eol = 18,
  aux_sym_document_repeat1 = 19,
  aux_sym_section_repeat1 = 20,
  aux_sym_dialog_repeat1 = 21,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_name_section] = "name",
  [sym_stop_section] = "stop_section",
  [sym_comment] = "comment",
  [aux_sym_narrative_token1] = "narrative_token1",
  [aux_sym_narrative_token2] = "narrative_token2",
  [anon_sym_u2014] = "\u2014",
  [aux_sym__open_dialog_token1] = "_open_dialog_token1",
  [aux_sym__open_narrative_token1] = "_open_narrative_token1",
  [anon_sym_LF] = "\n",
  [sym_document] = "document",
  [sym_section] = "section",
  [sym_narrative] = "narrative",
  [sym_dialog] = "dialog",
  [sym__open_dialog] = "speech",
  [sym__end_dialog] = "speech",
  [sym__open_narrative] = "narrative",
  [sym__end_narrative] = "narrative",
  [sym__eol] = "_eol",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_section_repeat1] = "section_repeat1",
  [aux_sym_dialog_repeat1] = "dialog_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_name_section] = sym_name_section,
  [sym_stop_section] = sym_stop_section,
  [sym_comment] = sym_comment,
  [aux_sym_narrative_token1] = aux_sym_narrative_token1,
  [aux_sym_narrative_token2] = aux_sym_narrative_token2,
  [anon_sym_u2014] = anon_sym_u2014,
  [aux_sym__open_dialog_token1] = aux_sym__open_dialog_token1,
  [aux_sym__open_narrative_token1] = aux_sym__open_narrative_token1,
  [anon_sym_LF] = anon_sym_LF,
  [sym_document] = sym_document,
  [sym_section] = sym_section,
  [sym_narrative] = sym_narrative,
  [sym_dialog] = sym_dialog,
  [sym__open_dialog] = sym__open_dialog,
  [sym__end_dialog] = sym__open_dialog,
  [sym__open_narrative] = sym_narrative,
  [sym__end_narrative] = sym_narrative,
  [sym__eol] = sym__eol,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_section_repeat1] = aux_sym_section_repeat1,
  [aux_sym_dialog_repeat1] = aux_sym_dialog_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_name_section] = {
    .visible = true,
    .named = true,
  },
  [sym_stop_section] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_narrative_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_narrative_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_u2014] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__open_dialog_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__open_narrative_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_narrative] = {
    .visible = true,
    .named = true,
  },
  [sym_dialog] = {
    .visible = true,
    .named = true,
  },
  [sym__open_dialog] = {
    .visible = true,
    .named = true,
  },
  [sym__end_dialog] = {
    .visible = true,
    .named = true,
  },
  [sym__open_narrative] = {
    .visible = true,
    .named = true,
  },
  [sym__end_narrative] = {
    .visible = true,
    .named = true,
  },
  [sym__eol] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dialog_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 13,
  [15] = 12,
  [16] = 10,
  [17] = 17,
  [18] = 7,
  [19] = 8,
  [20] = 11,
  [21] = 21,
  [22] = 9,
  [23] = 23,
  [24] = 23,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 29,
  [32] = 25,
  [33] = 28,
  [34] = 27,
  [35] = 30,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 37,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 45,
  [47] = 47,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      if (lookahead == '\t') ADVANCE(1);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == ' ') ADVANCE(18);
      if (lookahead == '<') ADVANCE(22);
      if (lookahead == '>') ADVANCE(9);
      if (lookahead == 0x2014) ADVANCE(27);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(19);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 1:
      if (lookahead == '\t') ADVANCE(1);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == ' ') ADVANCE(18);
      if (lookahead == '<') ADVANCE(23);
      if (lookahead == '>') ADVANCE(9);
      if (lookahead == 0x2014) ADVANCE(28);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(18);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 2:
      if (lookahead == '\t') ADVANCE(2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == ' ') ADVANCE(20);
      if (lookahead == '>') ADVANCE(9);
      if (lookahead == 0x2014) ADVANCE(28);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(20);
      if (lookahead != 0) ADVANCE(24);
      END_STATE();
    case 3:
      if (lookahead == '\t') SKIP(3);
      if (lookahead == '\n') ADVANCE(34);
      if ((0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(26);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(33);
      if (lookahead == 0x2014) ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      END_STATE();
    case 6:
      if (lookahead == '\n') SKIP(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0 &&
          lookahead != 0x2014) ADVANCE(30);
      END_STATE();
    case 7:
      if (lookahead == 0x2014) ADVANCE(27);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      END_STATE();
    case 8:
      if (lookahead == '\t' ||
          lookahead == '\n') SKIP(8);
      if ((0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '>' &&
          lookahead != 0x2014) ADVANCE(32);
      END_STATE();
    case 9:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(12);
      END_STATE();
    case 10:
      if (eof) ADVANCE(11);
      if (lookahead == '\t') ADVANCE(2);
      if (lookahead == '\n') SKIP(10);
      if (lookahead == ' ') ADVANCE(20);
      if (lookahead == '>') ADVANCE(9);
      if (lookahead == 0x2014) ADVANCE(27);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(21);
      if (lookahead != 0) ADVANCE(17);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_name_section);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_stop_section);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\t') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(18);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(19);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\t') ADVANCE(2);
      if (lookahead == ' ') ADVANCE(20);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(21);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(aux_sym_narrative_token1);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(aux_sym_narrative_token1);
      if (lookahead == '\t') ADVANCE(1);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == ' ') ADVANCE(18);
      if (lookahead == '<') ADVANCE(23);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(18);
      if (lookahead != 0 &&
          lookahead != '>' &&
          lookahead != 0x2014) ADVANCE(24);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym_narrative_token1);
      if (lookahead == '\t') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(18);
      if (lookahead == '<') ADVANCE(22);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(19);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '>' &&
          lookahead != 0x2014) ADVANCE(17);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym_narrative_token1);
      if (lookahead == '\t') ADVANCE(2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == ' ') ADVANCE(20);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '>' &&
          lookahead != 0x2014) ADVANCE(24);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_narrative_token1);
      if (lookahead == '\t') ADVANCE(2);
      if (lookahead == ' ') ADVANCE(20);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(21);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '>' &&
          lookahead != 0x2014) ADVANCE(17);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_narrative_token1);
      if (lookahead == '\n') ADVANCE(13);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_narrative_token1);
      if (lookahead == '\n') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(4);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_narrative_token1);
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(4);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_narrative_token2);
      if (lookahead == '\n') ADVANCE(34);
      if ((0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '>') ADVANCE(26);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_narrative_token2);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '>') ADVANCE(26);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_u2014);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(anon_sym_u2014);
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(4);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym__open_dialog_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(29);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x2014) ADVANCE(30);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym__open_dialog_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x2014) ADVANCE(30);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym__open_narrative_token1);
      if ((0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '>' &&
          lookahead != 0x2014) ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym__open_narrative_token1);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '>' &&
          lookahead != 0x2014) ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(33);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(34);
      if ((0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(25);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 10},
  [2] = {.lex_state = 10},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 10},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 10},
  [15] = {.lex_state = 10},
  [16] = {.lex_state = 10},
  [17] = {.lex_state = 10},
  [18] = {.lex_state = 10},
  [19] = {.lex_state = 10},
  [20] = {.lex_state = 10},
  [21] = {.lex_state = 10},
  [22] = {.lex_state = 10},
  [23] = {.lex_state = 7},
  [24] = {.lex_state = 7},
  [25] = {.lex_state = 5},
  [26] = {.lex_state = 7},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 8},
  [29] = {.lex_state = 5},
  [30] = {.lex_state = 8},
  [31] = {.lex_state = 5},
  [32] = {.lex_state = 5},
  [33] = {.lex_state = 8},
  [34] = {.lex_state = 3},
  [35] = {.lex_state = 8},
  [36] = {.lex_state = 8},
  [37] = {.lex_state = 5},
  [38] = {.lex_state = 5},
  [39] = {.lex_state = 5},
  [40] = {.lex_state = 8},
  [41] = {.lex_state = 7},
  [42] = {.lex_state = 7},
  [43] = {.lex_state = 7},
  [44] = {.lex_state = 6},
  [45] = {.lex_state = 6},
  [46] = {.lex_state = 6},
  [47] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_name_section] = ACTIONS(1),
    [sym_stop_section] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [aux_sym_narrative_token1] = ACTIONS(1),
    [anon_sym_u2014] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(47),
    [sym_section] = STATE(2),
    [sym_narrative] = STATE(2),
    [sym_dialog] = STATE(2),
    [sym__open_dialog] = STATE(30),
    [sym__end_dialog] = STATE(22),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_dialog_repeat1] = STATE(23),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_name_section] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
    [aux_sym_narrative_token1] = ACTIONS(9),
    [anon_sym_u2014] = ACTIONS(11),
  },
  [STATE(2)] = {
    [sym_section] = STATE(4),
    [sym_narrative] = STATE(4),
    [sym_dialog] = STATE(4),
    [sym__open_dialog] = STATE(30),
    [sym__end_dialog] = STATE(22),
    [aux_sym_document_repeat1] = STATE(4),
    [aux_sym_dialog_repeat1] = STATE(23),
    [ts_builtin_sym_end] = ACTIONS(13),
    [sym_name_section] = ACTIONS(5),
    [sym_comment] = ACTIONS(15),
    [aux_sym_narrative_token1] = ACTIONS(9),
    [anon_sym_u2014] = ACTIONS(11),
  },
  [STATE(3)] = {
    [sym_narrative] = STATE(5),
    [sym_dialog] = STATE(5),
    [sym__open_dialog] = STATE(35),
    [sym__end_dialog] = STATE(9),
    [aux_sym_section_repeat1] = STATE(5),
    [aux_sym_dialog_repeat1] = STATE(24),
    [ts_builtin_sym_end] = ACTIONS(17),
    [sym_name_section] = ACTIONS(19),
    [sym_stop_section] = ACTIONS(21),
    [sym_comment] = ACTIONS(23),
    [aux_sym_narrative_token1] = ACTIONS(25),
    [anon_sym_u2014] = ACTIONS(27),
  },
  [STATE(4)] = {
    [sym_section] = STATE(4),
    [sym_narrative] = STATE(4),
    [sym_dialog] = STATE(4),
    [sym__open_dialog] = STATE(30),
    [sym__end_dialog] = STATE(22),
    [aux_sym_document_repeat1] = STATE(4),
    [aux_sym_dialog_repeat1] = STATE(23),
    [ts_builtin_sym_end] = ACTIONS(29),
    [sym_name_section] = ACTIONS(31),
    [sym_comment] = ACTIONS(34),
    [aux_sym_narrative_token1] = ACTIONS(37),
    [anon_sym_u2014] = ACTIONS(40),
  },
  [STATE(5)] = {
    [sym_narrative] = STATE(6),
    [sym_dialog] = STATE(6),
    [sym__open_dialog] = STATE(35),
    [sym__end_dialog] = STATE(9),
    [aux_sym_section_repeat1] = STATE(6),
    [aux_sym_dialog_repeat1] = STATE(24),
    [ts_builtin_sym_end] = ACTIONS(43),
    [sym_name_section] = ACTIONS(45),
    [sym_stop_section] = ACTIONS(47),
    [sym_comment] = ACTIONS(49),
    [aux_sym_narrative_token1] = ACTIONS(25),
    [anon_sym_u2014] = ACTIONS(27),
  },
  [STATE(6)] = {
    [sym_narrative] = STATE(6),
    [sym_dialog] = STATE(6),
    [sym__open_dialog] = STATE(35),
    [sym__end_dialog] = STATE(9),
    [aux_sym_section_repeat1] = STATE(6),
    [aux_sym_dialog_repeat1] = STATE(24),
    [ts_builtin_sym_end] = ACTIONS(51),
    [sym_name_section] = ACTIONS(53),
    [sym_stop_section] = ACTIONS(53),
    [sym_comment] = ACTIONS(55),
    [aux_sym_narrative_token1] = ACTIONS(58),
    [anon_sym_u2014] = ACTIONS(61),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(64), 1,
      ts_builtin_sym_end,
    ACTIONS(66), 5,
      sym_name_section,
      sym_stop_section,
      sym_comment,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [11] = 2,
    ACTIONS(68), 1,
      ts_builtin_sym_end,
    ACTIONS(70), 5,
      sym_name_section,
      sym_stop_section,
      sym_comment,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [22] = 2,
    ACTIONS(72), 1,
      ts_builtin_sym_end,
    ACTIONS(74), 5,
      sym_name_section,
      sym_stop_section,
      sym_comment,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [33] = 2,
    ACTIONS(76), 1,
      ts_builtin_sym_end,
    ACTIONS(78), 5,
      sym_name_section,
      sym_stop_section,
      sym_comment,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [44] = 2,
    ACTIONS(80), 1,
      ts_builtin_sym_end,
    ACTIONS(82), 5,
      sym_name_section,
      sym_stop_section,
      sym_comment,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [55] = 2,
    ACTIONS(84), 1,
      ts_builtin_sym_end,
    ACTIONS(86), 5,
      sym_name_section,
      sym_stop_section,
      sym_comment,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [66] = 2,
    ACTIONS(88), 1,
      ts_builtin_sym_end,
    ACTIONS(90), 5,
      sym_name_section,
      sym_stop_section,
      sym_comment,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [77] = 2,
    ACTIONS(88), 1,
      ts_builtin_sym_end,
    ACTIONS(90), 4,
      sym_name_section,
      sym_comment,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [87] = 2,
    ACTIONS(84), 1,
      ts_builtin_sym_end,
    ACTIONS(86), 4,
      sym_name_section,
      sym_comment,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [97] = 2,
    ACTIONS(76), 1,
      ts_builtin_sym_end,
    ACTIONS(78), 4,
      sym_name_section,
      sym_comment,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [107] = 2,
    ACTIONS(43), 1,
      ts_builtin_sym_end,
    ACTIONS(45), 4,
      sym_name_section,
      sym_comment,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [117] = 2,
    ACTIONS(64), 1,
      ts_builtin_sym_end,
    ACTIONS(66), 4,
      sym_name_section,
      sym_comment,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [127] = 2,
    ACTIONS(68), 1,
      ts_builtin_sym_end,
    ACTIONS(70), 4,
      sym_name_section,
      sym_comment,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [137] = 2,
    ACTIONS(80), 1,
      ts_builtin_sym_end,
    ACTIONS(82), 4,
      sym_name_section,
      sym_comment,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [147] = 2,
    ACTIONS(92), 1,
      ts_builtin_sym_end,
    ACTIONS(94), 4,
      sym_name_section,
      sym_comment,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [157] = 2,
    ACTIONS(72), 1,
      ts_builtin_sym_end,
    ACTIONS(74), 4,
      sym_name_section,
      sym_comment,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [167] = 4,
    ACTIONS(96), 1,
      anon_sym_u2014,
    STATE(19), 1,
      sym__end_dialog,
    STATE(26), 1,
      aux_sym_dialog_repeat1,
    STATE(28), 1,
      sym__open_dialog,
  [180] = 4,
    ACTIONS(98), 1,
      anon_sym_u2014,
    STATE(8), 1,
      sym__end_dialog,
    STATE(26), 1,
      aux_sym_dialog_repeat1,
    STATE(33), 1,
      sym__open_dialog,
  [193] = 3,
    ACTIONS(100), 1,
      anon_sym_u2014,
    ACTIONS(102), 1,
      anon_sym_LF,
    STATE(15), 1,
      sym__eol,
  [203] = 3,
    ACTIONS(104), 1,
      anon_sym_u2014,
    STATE(26), 1,
      aux_sym_dialog_repeat1,
    STATE(36), 1,
      sym__open_dialog,
  [213] = 3,
    ACTIONS(107), 1,
      aux_sym_narrative_token2,
    ACTIONS(109), 1,
      anon_sym_LF,
    STATE(16), 1,
      sym__eol,
  [223] = 3,
    ACTIONS(111), 1,
      aux_sym__open_narrative_token1,
    STATE(14), 1,
      sym__end_narrative,
    STATE(41), 1,
      sym__open_narrative,
  [233] = 3,
    ACTIONS(113), 1,
      anon_sym_u2014,
    ACTIONS(115), 1,
      anon_sym_LF,
    STATE(18), 1,
      sym__eol,
  [243] = 3,
    ACTIONS(111), 1,
      aux_sym__open_narrative_token1,
    STATE(19), 1,
      sym__end_narrative,
    STATE(41), 1,
      sym__open_narrative,
  [253] = 3,
    ACTIONS(113), 1,
      anon_sym_u2014,
    ACTIONS(117), 1,
      anon_sym_LF,
    STATE(7), 1,
      sym__eol,
  [263] = 3,
    ACTIONS(100), 1,
      anon_sym_u2014,
    ACTIONS(119), 1,
      anon_sym_LF,
    STATE(12), 1,
      sym__eol,
  [273] = 3,
    ACTIONS(121), 1,
      aux_sym__open_narrative_token1,
    STATE(13), 1,
      sym__end_narrative,
    STATE(41), 1,
      sym__open_narrative,
  [283] = 3,
    ACTIONS(123), 1,
      aux_sym_narrative_token2,
    ACTIONS(125), 1,
      anon_sym_LF,
    STATE(10), 1,
      sym__eol,
  [293] = 3,
    ACTIONS(121), 1,
      aux_sym__open_narrative_token1,
    STATE(8), 1,
      sym__end_narrative,
    STATE(41), 1,
      sym__open_narrative,
  [303] = 2,
    ACTIONS(127), 1,
      aux_sym__open_narrative_token1,
    STATE(41), 1,
      sym__open_narrative,
  [310] = 2,
    ACTIONS(129), 1,
      anon_sym_LF,
    STATE(11), 1,
      sym__eol,
  [317] = 2,
    ACTIONS(131), 1,
      anon_sym_LF,
    STATE(3), 1,
      sym__eol,
  [324] = 2,
    ACTIONS(133), 1,
      anon_sym_LF,
    STATE(20), 1,
      sym__eol,
  [331] = 1,
    ACTIONS(135), 1,
      aux_sym__open_narrative_token1,
  [335] = 1,
    ACTIONS(137), 1,
      anon_sym_u2014,
  [339] = 1,
    ACTIONS(139), 1,
      anon_sym_u2014,
  [343] = 1,
    ACTIONS(141), 1,
      anon_sym_u2014,
  [347] = 1,
    ACTIONS(143), 1,
      aux_sym__open_dialog_token1,
  [351] = 1,
    ACTIONS(145), 1,
      aux_sym__open_dialog_token1,
  [355] = 1,
    ACTIONS(147), 1,
      aux_sym__open_dialog_token1,
  [359] = 1,
    ACTIONS(149), 1,
      ts_builtin_sym_end,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 11,
  [SMALL_STATE(9)] = 22,
  [SMALL_STATE(10)] = 33,
  [SMALL_STATE(11)] = 44,
  [SMALL_STATE(12)] = 55,
  [SMALL_STATE(13)] = 66,
  [SMALL_STATE(14)] = 77,
  [SMALL_STATE(15)] = 87,
  [SMALL_STATE(16)] = 97,
  [SMALL_STATE(17)] = 107,
  [SMALL_STATE(18)] = 117,
  [SMALL_STATE(19)] = 127,
  [SMALL_STATE(20)] = 137,
  [SMALL_STATE(21)] = 147,
  [SMALL_STATE(22)] = 157,
  [SMALL_STATE(23)] = 167,
  [SMALL_STATE(24)] = 180,
  [SMALL_STATE(25)] = 193,
  [SMALL_STATE(26)] = 203,
  [SMALL_STATE(27)] = 213,
  [SMALL_STATE(28)] = 223,
  [SMALL_STATE(29)] = 233,
  [SMALL_STATE(30)] = 243,
  [SMALL_STATE(31)] = 253,
  [SMALL_STATE(32)] = 263,
  [SMALL_STATE(33)] = 273,
  [SMALL_STATE(34)] = 283,
  [SMALL_STATE(35)] = 293,
  [SMALL_STATE(36)] = 303,
  [SMALL_STATE(37)] = 310,
  [SMALL_STATE(38)] = 317,
  [SMALL_STATE(39)] = 324,
  [SMALL_STATE(40)] = 331,
  [SMALL_STATE(41)] = 335,
  [SMALL_STATE(42)] = 339,
  [SMALL_STATE(43)] = 343,
  [SMALL_STATE(44)] = 347,
  [SMALL_STATE(45)] = 351,
  [SMALL_STATE(46)] = 355,
  [SMALL_STATE(47)] = 359,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [17] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 2, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 2, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [34] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [37] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(46),
  [43] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 3, 0, 0),
  [45] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 3, 0, 0),
  [47] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [49] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [51] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0),
  [53] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0),
  [55] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [58] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [61] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [64] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__end_narrative, 2, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__end_narrative, 2, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dialog, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dialog, 2, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dialog, 1, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dialog, 1, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_narrative, 2, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_narrative, 2, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_narrative, 3, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_narrative, 3, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__end_dialog, 3, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__end_dialog, 3, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dialog, 3, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dialog, 3, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 4, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 4, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [100] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [104] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dialog_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [107] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(16),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__open_narrative, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__open_dialog, 3, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dialog_repeat1, 2, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [141] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__open_narrative, 1, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(25),
  [149] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_draft(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "draft",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
