/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 50
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 23
#define ALIAS_COUNT 0
#define TOKEN_COUNT 11
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_name_section = 1,
  sym_stop_section = 2,
  sym_comment = 3,
  sym_tag = 4,
  aux_sym_narrative_token1 = 5,
  aux_sym_narrative_token2 = 6,
  anon_sym_u2014 = 7,
  aux_sym__open_dialog_token1 = 8,
  aux_sym__open_narrative_token1 = 9,
  anon_sym_LF = 10,
  sym_document = 11,
  sym_section = 12,
  sym_narrative = 13,
  sym_dialog = 14,
  sym__open_dialog = 15,
  sym__end_dialog = 16,
  sym__open_narrative = 17,
  sym__end_narrative = 18,
  sym__eol = 19,
  aux_sym_document_repeat1 = 20,
  aux_sym_section_repeat1 = 21,
  aux_sym_dialog_repeat1 = 22,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_name_section] = "name",
  [sym_stop_section] = "stop_section",
  [sym_comment] = "comment",
  [sym_tag] = "tag",
  [aux_sym_narrative_token1] = "narrative_token1",
  [aux_sym_narrative_token2] = "narrative_token2",
  [anon_sym_u2014] = "\u2014",
  [aux_sym__open_dialog_token1] = "_open_dialog_token1",
  [aux_sym__open_narrative_token1] = "_open_narrative_token1",
  [anon_sym_LF] = "\n",
  [sym_document] = "document",
  [sym_section] = "section",
  [sym_narrative] = "narrative",
  [sym_dialog] = "dialog",
  [sym__open_dialog] = "speech",
  [sym__end_dialog] = "speech",
  [sym__open_narrative] = "narrative",
  [sym__end_narrative] = "narrative",
  [sym__eol] = "_eol",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_section_repeat1] = "section_repeat1",
  [aux_sym_dialog_repeat1] = "dialog_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_name_section] = sym_name_section,
  [sym_stop_section] = sym_stop_section,
  [sym_comment] = sym_comment,
  [sym_tag] = sym_tag,
  [aux_sym_narrative_token1] = aux_sym_narrative_token1,
  [aux_sym_narrative_token2] = aux_sym_narrative_token2,
  [anon_sym_u2014] = anon_sym_u2014,
  [aux_sym__open_dialog_token1] = aux_sym__open_dialog_token1,
  [aux_sym__open_narrative_token1] = aux_sym__open_narrative_token1,
  [anon_sym_LF] = anon_sym_LF,
  [sym_document] = sym_document,
  [sym_section] = sym_section,
  [sym_narrative] = sym_narrative,
  [sym_dialog] = sym_dialog,
  [sym__open_dialog] = sym__open_dialog,
  [sym__end_dialog] = sym__open_dialog,
  [sym__open_narrative] = sym_narrative,
  [sym__end_narrative] = sym_narrative,
  [sym__eol] = sym__eol,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_section_repeat1] = aux_sym_section_repeat1,
  [aux_sym_dialog_repeat1] = aux_sym_dialog_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_name_section] = {
    .visible = true,
    .named = true,
  },
  [sym_stop_section] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_narrative_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_narrative_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_u2014] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__open_dialog_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__open_narrative_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_narrative] = {
    .visible = true,
    .named = true,
  },
  [sym_dialog] = {
    .visible = true,
    .named = true,
  },
  [sym__open_dialog] = {
    .visible = true,
    .named = true,
  },
  [sym__end_dialog] = {
    .visible = true,
    .named = true,
  },
  [sym__open_narrative] = {
    .visible = true,
    .named = true,
  },
  [sym__end_narrative] = {
    .visible = true,
    .named = true,
  },
  [sym__eol] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dialog_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 8,
  [15] = 12,
  [16] = 11,
  [17] = 17,
  [18] = 7,
  [19] = 13,
  [20] = 9,
  [21] = 21,
  [22] = 22,
  [23] = 10,
  [24] = 24,
  [25] = 24,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 28,
  [32] = 26,
  [33] = 33,
  [34] = 30,
  [35] = 27,
  [36] = 33,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 37,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 43,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(11);
      if (lookahead == '\t') ADVANCE(1);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == ' ') ADVANCE(22);
      if (lookahead == '#') ADVANCE(30);
      if (lookahead == '<') ADVANCE(26);
      if (lookahead == '>') ADVANCE(9);
      if (lookahead == 0x2014) ADVANCE(33);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(23);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 1:
      if (lookahead == '\t') ADVANCE(1);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == ' ') ADVANCE(22);
      if (lookahead == '#') ADVANCE(28);
      if (lookahead == '<') ADVANCE(27);
      if (lookahead == '>') ADVANCE(9);
      if (lookahead == 0x2014) ADVANCE(34);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(22);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 2:
      if (lookahead == '\t') ADVANCE(2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == ' ') ADVANCE(24);
      if (lookahead == '#') ADVANCE(28);
      if (lookahead == '>') ADVANCE(9);
      if (lookahead == 0x2014) ADVANCE(34);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(24);
      if (lookahead != 0) ADVANCE(29);
      END_STATE();
    case 3:
      if (lookahead == '\t') SKIP(3);
      if (lookahead == '\n') ADVANCE(39);
      if ((0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(32);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(40);
      if (lookahead == 0x2014) ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      END_STATE();
    case 6:
      if (lookahead == '\n') SKIP(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != 0x2014) ADVANCE(36);
      END_STATE();
    case 7:
      if (lookahead == 0x2014) ADVANCE(33);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      END_STATE();
    case 8:
      if (lookahead == '\t' ||
          lookahead == '\n') SKIP(8);
      if ((0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != '>' &&
          lookahead != 0x2014) ADVANCE(38);
      END_STATE();
    case 9:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(12);
      END_STATE();
    case 10:
      if (eof) ADVANCE(11);
      if (lookahead == '\t') ADVANCE(2);
      if (lookahead == '\n') SKIP(10);
      if (lookahead == ' ') ADVANCE(24);
      if (lookahead == '#') ADVANCE(30);
      if (lookahead == '>') ADVANCE(9);
      if (lookahead == 0x2014) ADVANCE(33);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(25);
      if (lookahead != 0) ADVANCE(21);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(sym_name_section);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(12);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_stop_section);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\t') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(22);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(23);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\t') ADVANCE(2);
      if (lookahead == ' ') ADVANCE(24);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(25);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_tag);
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead == '#') ADVANCE(17);
      if (lookahead == '>') ADVANCE(20);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_tag);
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead == '>') ADVANCE(20);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_tag);
      if (lookahead == '#') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_tag);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym_narrative_token1);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_narrative_token1);
      if (lookahead == '\t') ADVANCE(1);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == ' ') ADVANCE(22);
      if (lookahead == '#') ADVANCE(28);
      if (lookahead == '<') ADVANCE(27);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(22);
      if (lookahead != 0 &&
          lookahead != '>' &&
          lookahead != 0x2014) ADVANCE(29);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_narrative_token1);
      if (lookahead == '\t') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(22);
      if (lookahead == '#') ADVANCE(30);
      if (lookahead == '<') ADVANCE(26);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(23);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '>' &&
          lookahead != 0x2014) ADVANCE(21);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_narrative_token1);
      if (lookahead == '\t') ADVANCE(2);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == ' ') ADVANCE(24);
      if (lookahead == '#') ADVANCE(28);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(24);
      if (lookahead != 0 &&
          lookahead != '>' &&
          lookahead != 0x2014) ADVANCE(29);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_narrative_token1);
      if (lookahead == '\t') ADVANCE(2);
      if (lookahead == ' ') ADVANCE(24);
      if (lookahead == '#') ADVANCE(30);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(25);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '>' &&
          lookahead != 0x2014) ADVANCE(21);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_narrative_token1);
      if (lookahead == '\n') ADVANCE(13);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_narrative_token1);
      if (lookahead == '\n') ADVANCE(13);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(4);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_narrative_token1);
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead == '#') ADVANCE(17);
      if (lookahead == '>') ADVANCE(20);
      if (lookahead != 0) ADVANCE(18);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_narrative_token1);
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(4);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_narrative_token1);
      if (lookahead == '#') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(20);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_narrative_token2);
      if (lookahead == '\n') ADVANCE(39);
      if ((0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '>') ADVANCE(32);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_narrative_token2);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '>') ADVANCE(32);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(anon_sym_u2014);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(anon_sym_u2014);
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(4);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(aux_sym__open_dialog_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x2014) ADVANCE(36);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(aux_sym__open_dialog_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x2014) ADVANCE(36);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym__open_narrative_token1);
      if ((0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '>' &&
          lookahead != 0x2014) ADVANCE(38);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym__open_narrative_token1);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '>' &&
          lookahead != 0x2014) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(39);
      if ((0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(31);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(40);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 10},
  [2] = {.lex_state = 10},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 10},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 10},
  [15] = {.lex_state = 10},
  [16] = {.lex_state = 10},
  [17] = {.lex_state = 10},
  [18] = {.lex_state = 10},
  [19] = {.lex_state = 10},
  [20] = {.lex_state = 10},
  [21] = {.lex_state = 10},
  [22] = {.lex_state = 10},
  [23] = {.lex_state = 10},
  [24] = {.lex_state = 7},
  [25] = {.lex_state = 7},
  [26] = {.lex_state = 8},
  [27] = {.lex_state = 3},
  [28] = {.lex_state = 5},
  [29] = {.lex_state = 7},
  [30] = {.lex_state = 5},
  [31] = {.lex_state = 5},
  [32] = {.lex_state = 8},
  [33] = {.lex_state = 8},
  [34] = {.lex_state = 5},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 8},
  [37] = {.lex_state = 5},
  [38] = {.lex_state = 8},
  [39] = {.lex_state = 5},
  [40] = {.lex_state = 5},
  [41] = {.lex_state = 5},
  [42] = {.lex_state = 8},
  [43] = {.lex_state = 6},
  [44] = {.lex_state = 6},
  [45] = {.lex_state = 0},
  [46] = {.lex_state = 7},
  [47] = {.lex_state = 7},
  [48] = {.lex_state = 7},
  [49] = {.lex_state = 6},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_name_section] = ACTIONS(1),
    [sym_stop_section] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_tag] = ACTIONS(1),
    [aux_sym_narrative_token1] = ACTIONS(1),
    [anon_sym_u2014] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(45),
    [sym_section] = STATE(2),
    [sym_narrative] = STATE(2),
    [sym_dialog] = STATE(2),
    [sym__open_dialog] = STATE(33),
    [sym__end_dialog] = STATE(20),
    [aux_sym_document_repeat1] = STATE(2),
    [aux_sym_dialog_repeat1] = STATE(24),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_name_section] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
    [sym_tag] = ACTIONS(9),
    [aux_sym_narrative_token1] = ACTIONS(11),
    [anon_sym_u2014] = ACTIONS(13),
  },
  [STATE(2)] = {
    [sym_section] = STATE(4),
    [sym_narrative] = STATE(4),
    [sym_dialog] = STATE(4),
    [sym__open_dialog] = STATE(33),
    [sym__end_dialog] = STATE(20),
    [aux_sym_document_repeat1] = STATE(4),
    [aux_sym_dialog_repeat1] = STATE(24),
    [ts_builtin_sym_end] = ACTIONS(15),
    [sym_name_section] = ACTIONS(5),
    [sym_comment] = ACTIONS(17),
    [sym_tag] = ACTIONS(9),
    [aux_sym_narrative_token1] = ACTIONS(11),
    [anon_sym_u2014] = ACTIONS(13),
  },
  [STATE(3)] = {
    [sym_narrative] = STATE(5),
    [sym_dialog] = STATE(5),
    [sym__open_dialog] = STATE(36),
    [sym__end_dialog] = STATE(9),
    [aux_sym_section_repeat1] = STATE(5),
    [aux_sym_dialog_repeat1] = STATE(25),
    [ts_builtin_sym_end] = ACTIONS(19),
    [sym_name_section] = ACTIONS(21),
    [sym_stop_section] = ACTIONS(23),
    [sym_comment] = ACTIONS(25),
    [sym_tag] = ACTIONS(21),
    [aux_sym_narrative_token1] = ACTIONS(27),
    [anon_sym_u2014] = ACTIONS(29),
  },
  [STATE(4)] = {
    [sym_section] = STATE(4),
    [sym_narrative] = STATE(4),
    [sym_dialog] = STATE(4),
    [sym__open_dialog] = STATE(33),
    [sym__end_dialog] = STATE(20),
    [aux_sym_document_repeat1] = STATE(4),
    [aux_sym_dialog_repeat1] = STATE(24),
    [ts_builtin_sym_end] = ACTIONS(31),
    [sym_name_section] = ACTIONS(33),
    [sym_comment] = ACTIONS(36),
    [sym_tag] = ACTIONS(39),
    [aux_sym_narrative_token1] = ACTIONS(42),
    [anon_sym_u2014] = ACTIONS(45),
  },
  [STATE(5)] = {
    [sym_narrative] = STATE(6),
    [sym_dialog] = STATE(6),
    [sym__open_dialog] = STATE(36),
    [sym__end_dialog] = STATE(9),
    [aux_sym_section_repeat1] = STATE(6),
    [aux_sym_dialog_repeat1] = STATE(25),
    [ts_builtin_sym_end] = ACTIONS(48),
    [sym_name_section] = ACTIONS(50),
    [sym_stop_section] = ACTIONS(52),
    [sym_comment] = ACTIONS(54),
    [sym_tag] = ACTIONS(50),
    [aux_sym_narrative_token1] = ACTIONS(27),
    [anon_sym_u2014] = ACTIONS(29),
  },
  [STATE(6)] = {
    [sym_narrative] = STATE(6),
    [sym_dialog] = STATE(6),
    [sym__open_dialog] = STATE(36),
    [sym__end_dialog] = STATE(9),
    [aux_sym_section_repeat1] = STATE(6),
    [aux_sym_dialog_repeat1] = STATE(25),
    [ts_builtin_sym_end] = ACTIONS(56),
    [sym_name_section] = ACTIONS(58),
    [sym_stop_section] = ACTIONS(58),
    [sym_comment] = ACTIONS(60),
    [sym_tag] = ACTIONS(58),
    [aux_sym_narrative_token1] = ACTIONS(63),
    [anon_sym_u2014] = ACTIONS(66),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 2,
    ACTIONS(69), 1,
      ts_builtin_sym_end,
    ACTIONS(71), 6,
      sym_name_section,
      sym_stop_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [12] = 2,
    ACTIONS(73), 1,
      ts_builtin_sym_end,
    ACTIONS(75), 6,
      sym_name_section,
      sym_stop_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [24] = 2,
    ACTIONS(77), 1,
      ts_builtin_sym_end,
    ACTIONS(79), 6,
      sym_name_section,
      sym_stop_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [36] = 2,
    ACTIONS(81), 1,
      ts_builtin_sym_end,
    ACTIONS(83), 6,
      sym_name_section,
      sym_stop_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [48] = 2,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
    ACTIONS(87), 6,
      sym_name_section,
      sym_stop_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [60] = 2,
    ACTIONS(89), 1,
      ts_builtin_sym_end,
    ACTIONS(91), 6,
      sym_name_section,
      sym_stop_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [72] = 2,
    ACTIONS(93), 1,
      ts_builtin_sym_end,
    ACTIONS(95), 6,
      sym_name_section,
      sym_stop_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [84] = 2,
    ACTIONS(73), 1,
      ts_builtin_sym_end,
    ACTIONS(75), 5,
      sym_name_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [95] = 2,
    ACTIONS(89), 1,
      ts_builtin_sym_end,
    ACTIONS(91), 5,
      sym_name_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [106] = 2,
    ACTIONS(85), 1,
      ts_builtin_sym_end,
    ACTIONS(87), 5,
      sym_name_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [117] = 2,
    ACTIONS(48), 1,
      ts_builtin_sym_end,
    ACTIONS(50), 5,
      sym_name_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [128] = 2,
    ACTIONS(69), 1,
      ts_builtin_sym_end,
    ACTIONS(71), 5,
      sym_name_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [139] = 2,
    ACTIONS(93), 1,
      ts_builtin_sym_end,
    ACTIONS(95), 5,
      sym_name_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [150] = 2,
    ACTIONS(77), 1,
      ts_builtin_sym_end,
    ACTIONS(79), 5,
      sym_name_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [161] = 2,
    ACTIONS(97), 1,
      ts_builtin_sym_end,
    ACTIONS(99), 5,
      sym_name_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [172] = 2,
    ACTIONS(31), 1,
      ts_builtin_sym_end,
    ACTIONS(101), 5,
      sym_name_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [183] = 2,
    ACTIONS(81), 1,
      ts_builtin_sym_end,
    ACTIONS(83), 5,
      sym_name_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [194] = 4,
    ACTIONS(103), 1,
      anon_sym_u2014,
    STATE(16), 1,
      sym__end_dialog,
    STATE(26), 1,
      sym__open_dialog,
    STATE(29), 1,
      aux_sym_dialog_repeat1,
  [207] = 4,
    ACTIONS(105), 1,
      anon_sym_u2014,
    STATE(11), 1,
      sym__end_dialog,
    STATE(29), 1,
      aux_sym_dialog_repeat1,
    STATE(32), 1,
      sym__open_dialog,
  [220] = 3,
    ACTIONS(107), 1,
      aux_sym__open_narrative_token1,
    STATE(14), 1,
      sym__end_narrative,
    STATE(48), 1,
      sym__open_narrative,
  [230] = 3,
    ACTIONS(109), 1,
      aux_sym_narrative_token2,
    ACTIONS(111), 1,
      anon_sym_LF,
    STATE(23), 1,
      sym__eol,
  [240] = 3,
    ACTIONS(113), 1,
      anon_sym_u2014,
    ACTIONS(115), 1,
      anon_sym_LF,
    STATE(19), 1,
      sym__eol,
  [250] = 3,
    ACTIONS(117), 1,
      anon_sym_u2014,
    STATE(29), 1,
      aux_sym_dialog_repeat1,
    STATE(38), 1,
      sym__open_dialog,
  [260] = 3,
    ACTIONS(120), 1,
      anon_sym_u2014,
    ACTIONS(122), 1,
      anon_sym_LF,
    STATE(12), 1,
      sym__eol,
  [270] = 3,
    ACTIONS(113), 1,
      anon_sym_u2014,
    ACTIONS(124), 1,
      anon_sym_LF,
    STATE(13), 1,
      sym__eol,
  [280] = 3,
    ACTIONS(126), 1,
      aux_sym__open_narrative_token1,
    STATE(8), 1,
      sym__end_narrative,
    STATE(48), 1,
      sym__open_narrative,
  [290] = 3,
    ACTIONS(107), 1,
      aux_sym__open_narrative_token1,
    STATE(16), 1,
      sym__end_narrative,
    STATE(48), 1,
      sym__open_narrative,
  [300] = 3,
    ACTIONS(120), 1,
      anon_sym_u2014,
    ACTIONS(128), 1,
      anon_sym_LF,
    STATE(15), 1,
      sym__eol,
  [310] = 3,
    ACTIONS(130), 1,
      aux_sym_narrative_token2,
    ACTIONS(132), 1,
      anon_sym_LF,
    STATE(10), 1,
      sym__eol,
  [320] = 3,
    ACTIONS(126), 1,
      aux_sym__open_narrative_token1,
    STATE(11), 1,
      sym__end_narrative,
    STATE(48), 1,
      sym__open_narrative,
  [330] = 2,
    ACTIONS(134), 1,
      anon_sym_LF,
    STATE(18), 1,
      sym__eol,
  [337] = 2,
    ACTIONS(136), 1,
      aux_sym__open_narrative_token1,
    STATE(48), 1,
      sym__open_narrative,
  [344] = 2,
    ACTIONS(138), 1,
      anon_sym_LF,
    STATE(3), 1,
      sym__eol,
  [351] = 2,
    ACTIONS(140), 1,
      anon_sym_LF,
    STATE(7), 1,
      sym__eol,
  [358] = 2,
    ACTIONS(142), 1,
      anon_sym_LF,
    STATE(22), 1,
      sym__eol,
  [365] = 1,
    ACTIONS(144), 1,
      aux_sym__open_narrative_token1,
  [369] = 1,
    ACTIONS(146), 1,
      aux_sym__open_dialog_token1,
  [373] = 1,
    ACTIONS(148), 1,
      aux_sym__open_dialog_token1,
  [377] = 1,
    ACTIONS(150), 1,
      ts_builtin_sym_end,
  [381] = 1,
    ACTIONS(152), 1,
      anon_sym_u2014,
  [385] = 1,
    ACTIONS(154), 1,
      anon_sym_u2014,
  [389] = 1,
    ACTIONS(156), 1,
      anon_sym_u2014,
  [393] = 1,
    ACTIONS(158), 1,
      aux_sym__open_dialog_token1,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 12,
  [SMALL_STATE(9)] = 24,
  [SMALL_STATE(10)] = 36,
  [SMALL_STATE(11)] = 48,
  [SMALL_STATE(12)] = 60,
  [SMALL_STATE(13)] = 72,
  [SMALL_STATE(14)] = 84,
  [SMALL_STATE(15)] = 95,
  [SMALL_STATE(16)] = 106,
  [SMALL_STATE(17)] = 117,
  [SMALL_STATE(18)] = 128,
  [SMALL_STATE(19)] = 139,
  [SMALL_STATE(20)] = 150,
  [SMALL_STATE(21)] = 161,
  [SMALL_STATE(22)] = 172,
  [SMALL_STATE(23)] = 183,
  [SMALL_STATE(24)] = 194,
  [SMALL_STATE(25)] = 207,
  [SMALL_STATE(26)] = 220,
  [SMALL_STATE(27)] = 230,
  [SMALL_STATE(28)] = 240,
  [SMALL_STATE(29)] = 250,
  [SMALL_STATE(30)] = 260,
  [SMALL_STATE(31)] = 270,
  [SMALL_STATE(32)] = 280,
  [SMALL_STATE(33)] = 290,
  [SMALL_STATE(34)] = 300,
  [SMALL_STATE(35)] = 310,
  [SMALL_STATE(36)] = 320,
  [SMALL_STATE(37)] = 330,
  [SMALL_STATE(38)] = 337,
  [SMALL_STATE(39)] = 344,
  [SMALL_STATE(40)] = 351,
  [SMALL_STATE(41)] = 358,
  [SMALL_STATE(42)] = 365,
  [SMALL_STATE(43)] = 369,
  [SMALL_STATE(44)] = 373,
  [SMALL_STATE(45)] = 377,
  [SMALL_STATE(46)] = 381,
  [SMALL_STATE(47)] = 385,
  [SMALL_STATE(48)] = 389,
  [SMALL_STATE(49)] = 393,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(2),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 2, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 2, 0, 0),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [45] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [48] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 3, 0, 0),
  [50] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 3, 0, 0),
  [52] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [54] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [63] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [66] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [69] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_narrative, 3, 0, 0),
  [71] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_narrative, 3, 0, 0),
  [73] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dialog, 3, 0, 0),
  [75] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dialog, 3, 0, 0),
  [77] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dialog, 1, 0, 0),
  [79] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dialog, 1, 0, 0),
  [81] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_narrative, 2, 0, 0),
  [83] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_narrative, 2, 0, 0),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dialog, 2, 0, 0),
  [87] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dialog, 2, 0, 0),
  [89] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__end_dialog, 3, 0, 0),
  [91] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__end_dialog, 3, 0, 0),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__end_narrative, 2, 0, 0),
  [95] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__end_narrative, 2, 0, 0),
  [97] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 4, 0, 0),
  [99] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 4, 0, 0),
  [101] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [109] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(23),
  [113] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__open_narrative, 1, 0, 0),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(19),
  [117] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dialog_repeat1, 2, 0, 0), SHIFT_REPEAT(44),
  [120] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [122] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [124] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [126] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [128] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [130] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [132] = {.entry = {.count = 1, .reusable = false}}, SHIFT(10),
  [134] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [136] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [140] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [142] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__open_dialog, 3, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [148] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [150] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [152] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [154] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__open_narrative, 1, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dialog_repeat1, 2, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_draft(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "draft",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
