/* Automatically @generated by tree-sitter v0.25.10 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 54
#define LARGE_STATE_COUNT 7
#define SYMBOL_COUNT 24
#define ALIAS_COUNT 0
#define TOKEN_COUNT 11
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 1
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_name_section = 1,
  sym_stop_section = 2,
  sym_comment = 3,
  sym_tag = 4,
  aux_sym_narrative_token1 = 5,
  aux_sym_narrative_token2 = 6,
  anon_sym_u2014 = 7,
  aux_sym__open_dialog_token1 = 8,
  aux_sym__open_narrative_token1 = 9,
  anon_sym_LF = 10,
  sym_document = 11,
  sym_section = 12,
  sym_tag_line = 13,
  sym_narrative = 14,
  sym_dialog = 15,
  sym__open_dialog = 16,
  sym__end_dialog = 17,
  sym__open_narrative = 18,
  sym__end_narrative = 19,
  sym__eol = 20,
  aux_sym_document_repeat1 = 21,
  aux_sym_section_repeat1 = 22,
  aux_sym_dialog_repeat1 = 23,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_name_section] = "name",
  [sym_stop_section] = "stop_section",
  [sym_comment] = "comment",
  [sym_tag] = "tag",
  [aux_sym_narrative_token1] = "narrative_token1",
  [aux_sym_narrative_token2] = "narrative_token2",
  [anon_sym_u2014] = "\u2014",
  [aux_sym__open_dialog_token1] = "_open_dialog_token1",
  [aux_sym__open_narrative_token1] = "_open_narrative_token1",
  [anon_sym_LF] = "\n",
  [sym_document] = "document",
  [sym_section] = "section",
  [sym_tag_line] = "tag_line",
  [sym_narrative] = "narrative",
  [sym_dialog] = "dialog",
  [sym__open_dialog] = "speech",
  [sym__end_dialog] = "speech",
  [sym__open_narrative] = "narrative",
  [sym__end_narrative] = "narrative",
  [sym__eol] = "_eol",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_section_repeat1] = "section_repeat1",
  [aux_sym_dialog_repeat1] = "dialog_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_name_section] = sym_name_section,
  [sym_stop_section] = sym_stop_section,
  [sym_comment] = sym_comment,
  [sym_tag] = sym_tag,
  [aux_sym_narrative_token1] = aux_sym_narrative_token1,
  [aux_sym_narrative_token2] = aux_sym_narrative_token2,
  [anon_sym_u2014] = anon_sym_u2014,
  [aux_sym__open_dialog_token1] = aux_sym__open_dialog_token1,
  [aux_sym__open_narrative_token1] = aux_sym__open_narrative_token1,
  [anon_sym_LF] = anon_sym_LF,
  [sym_document] = sym_document,
  [sym_section] = sym_section,
  [sym_tag_line] = sym_tag_line,
  [sym_narrative] = sym_narrative,
  [sym_dialog] = sym_dialog,
  [sym__open_dialog] = sym__open_dialog,
  [sym__end_dialog] = sym__open_dialog,
  [sym__open_narrative] = sym_narrative,
  [sym__end_narrative] = sym_narrative,
  [sym__eol] = sym__eol,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_section_repeat1] = aux_sym_section_repeat1,
  [aux_sym_dialog_repeat1] = aux_sym_dialog_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_name_section] = {
    .visible = true,
    .named = true,
  },
  [sym_stop_section] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_tag] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_narrative_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_narrative_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_u2014] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__open_dialog_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym__open_narrative_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LF] = {
    .visible = true,
    .named = false,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym_section] = {
    .visible = true,
    .named = true,
  },
  [sym_tag_line] = {
    .visible = true,
    .named = true,
  },
  [sym_narrative] = {
    .visible = true,
    .named = true,
  },
  [sym_dialog] = {
    .visible = true,
    .named = true,
  },
  [sym__open_dialog] = {
    .visible = true,
    .named = true,
  },
  [sym__end_dialog] = {
    .visible = true,
    .named = true,
  },
  [sym__open_narrative] = {
    .visible = true,
    .named = true,
  },
  [sym__end_narrative] = {
    .visible = true,
    .named = true,
  },
  [sym__eol] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_section_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_dialog_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 7,
  [17] = 11,
  [18] = 13,
  [19] = 19,
  [20] = 12,
  [21] = 21,
  [22] = 14,
  [23] = 15,
  [24] = 8,
  [25] = 9,
  [26] = 10,
  [27] = 27,
  [28] = 27,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 29,
  [33] = 33,
  [34] = 31,
  [35] = 35,
  [36] = 33,
  [37] = 37,
  [38] = 37,
  [39] = 35,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 40,
  [45] = 43,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 48,
  [51] = 51,
  [52] = 52,
  [53] = 53,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      if (lookahead == '\t') ADVANCE(1);
      if (lookahead == '\n') SKIP(0);
      if (lookahead == ' ') ADVANCE(23);
      if (lookahead == '#') ADVANCE(31);
      if (lookahead == '<') ADVANCE(27);
      if (lookahead == '>') ADVANCE(10);
      if (lookahead == 0x2014) ADVANCE(35);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(24);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 1:
      if (lookahead == '\t') ADVANCE(1);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == ' ') ADVANCE(23);
      if (lookahead == '#') ADVANCE(29);
      if (lookahead == '<') ADVANCE(28);
      if (lookahead == '>') ADVANCE(10);
      if (lookahead == 0x2014) ADVANCE(36);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(23);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 2:
      if (lookahead == '\t') ADVANCE(2);
      if (lookahead == '\n') ADVANCE(17);
      if (lookahead == ' ') ADVANCE(25);
      if (lookahead == '#') ADVANCE(29);
      if (lookahead == '>') ADVANCE(10);
      if (lookahead == 0x2014) ADVANCE(36);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(25);
      if (lookahead != 0) ADVANCE(30);
      END_STATE();
    case 3:
      if (lookahead == '\t') SKIP(3);
      if (lookahead == '\n') ADVANCE(42);
      if ((0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(34);
      END_STATE();
    case 4:
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(4);
      END_STATE();
    case 5:
      if (lookahead == '\n') ADVANCE(41);
      if (lookahead == 0x2014) ADVANCE(35);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      END_STATE();
    case 6:
      if (lookahead == '\n') SKIP(6);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0 &&
          lookahead != 0x2014) ADVANCE(38);
      END_STATE();
    case 7:
      if (lookahead == 0x2014) ADVANCE(35);
      if (lookahead == '\t' ||
          lookahead == '\n') SKIP(7);
      if ((0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(22);
      END_STATE();
    case 8:
      if (lookahead == 0x2014) ADVANCE(35);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(8);
      END_STATE();
    case 9:
      if (lookahead == '\t' ||
          lookahead == '\n') SKIP(9);
      if ((0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(39);
      if (lookahead != 0 &&
          lookahead != '>' &&
          lookahead != 0x2014) ADVANCE(40);
      END_STATE();
    case 10:
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 11:
      if (eof) ADVANCE(12);
      if (lookahead == '\t') ADVANCE(2);
      if (lookahead == '\n') SKIP(11);
      if (lookahead == ' ') ADVANCE(25);
      if (lookahead == '#') ADVANCE(31);
      if (lookahead == '>') ADVANCE(10);
      if (lookahead == 0x2014) ADVANCE(35);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(26);
      if (lookahead != 0) ADVANCE(22);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(sym_name_section);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_stop_section);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_comment);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\t') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(23);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(24);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(sym_comment);
      if (lookahead == '\t') ADVANCE(2);
      if (lookahead == ' ') ADVANCE(25);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(26);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(sym_tag);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == '>') ADVANCE(21);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(sym_tag);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '>') ADVANCE(21);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_tag);
      if (lookahead == '#') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(21);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_tag);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym_narrative_token1);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym_narrative_token1);
      if (lookahead == '\t') ADVANCE(1);
      if (lookahead == '\n') ADVANCE(16);
      if (lookahead == ' ') ADVANCE(23);
      if (lookahead == '#') ADVANCE(29);
      if (lookahead == '<') ADVANCE(28);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(23);
      if (lookahead != 0 &&
          lookahead != '>' &&
          lookahead != 0x2014) ADVANCE(30);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(aux_sym_narrative_token1);
      if (lookahead == '\t') ADVANCE(1);
      if (lookahead == ' ') ADVANCE(23);
      if (lookahead == '#') ADVANCE(31);
      if (lookahead == '<') ADVANCE(27);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(24);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '>' &&
          lookahead != 0x2014) ADVANCE(22);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(aux_sym_narrative_token1);
      if (lookahead == '\t') ADVANCE(2);
      if (lookahead == '\n') ADVANCE(17);
      if (lookahead == ' ') ADVANCE(25);
      if (lookahead == '#') ADVANCE(29);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(25);
      if (lookahead != 0 &&
          lookahead != '>' &&
          lookahead != 0x2014) ADVANCE(30);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(aux_sym_narrative_token1);
      if (lookahead == '\t') ADVANCE(2);
      if (lookahead == ' ') ADVANCE(25);
      if (lookahead == '#') ADVANCE(31);
      if ((0x0b <= lookahead && lookahead <= '\r')) ADVANCE(26);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '>' &&
          lookahead != 0x2014) ADVANCE(22);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(aux_sym_narrative_token1);
      if (lookahead == '\n') ADVANCE(14);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(aux_sym_narrative_token1);
      if (lookahead == '\n') ADVANCE(14);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(4);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(aux_sym_narrative_token1);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead == '#') ADVANCE(18);
      if (lookahead == '>') ADVANCE(21);
      if (lookahead != 0) ADVANCE(19);
      END_STATE();
    case 30:
      ACCEPT_TOKEN(aux_sym_narrative_token1);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(4);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(aux_sym_narrative_token1);
      if (lookahead == '#') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(21);
      END_STATE();
    case 32:
      ACCEPT_TOKEN(aux_sym_narrative_token1);
      if ((0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(32);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '>' &&
          lookahead != 0x2014) ADVANCE(22);
      END_STATE();
    case 33:
      ACCEPT_TOKEN(aux_sym_narrative_token2);
      if (lookahead == '\n') ADVANCE(42);
      if ((0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '>') ADVANCE(34);
      END_STATE();
    case 34:
      ACCEPT_TOKEN(aux_sym_narrative_token2);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '>') ADVANCE(34);
      END_STATE();
    case 35:
      ACCEPT_TOKEN(anon_sym_u2014);
      END_STATE();
    case 36:
      ACCEPT_TOKEN(anon_sym_u2014);
      if (lookahead == '\n') ADVANCE(15);
      if (lookahead != 0 &&
          lookahead != '>') ADVANCE(4);
      END_STATE();
    case 37:
      ACCEPT_TOKEN(aux_sym__open_dialog_token1);
      if (lookahead == '\t' ||
          (0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(37);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != 0x2014) ADVANCE(38);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(aux_sym__open_dialog_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != 0x2014) ADVANCE(38);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(aux_sym__open_narrative_token1);
      if ((0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(39);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != '>' &&
          lookahead != 0x2014) ADVANCE(40);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(aux_sym__open_narrative_token1);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '>' &&
          lookahead != 0x2014) ADVANCE(40);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(41);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LF);
      if (lookahead == '\n') ADVANCE(42);
      if ((0x0b <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(33);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 11},
  [2] = {.lex_state = 0},
  [3] = {.lex_state = 0},
  [4] = {.lex_state = 11},
  [5] = {.lex_state = 0},
  [6] = {.lex_state = 11},
  [7] = {.lex_state = 7},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 7},
  [17] = {.lex_state = 11},
  [18] = {.lex_state = 11},
  [19] = {.lex_state = 11},
  [20] = {.lex_state = 11},
  [21] = {.lex_state = 11},
  [22] = {.lex_state = 11},
  [23] = {.lex_state = 11},
  [24] = {.lex_state = 11},
  [25] = {.lex_state = 11},
  [26] = {.lex_state = 11},
  [27] = {.lex_state = 8},
  [28] = {.lex_state = 8},
  [29] = {.lex_state = 5},
  [30] = {.lex_state = 8},
  [31] = {.lex_state = 9},
  [32] = {.lex_state = 5},
  [33] = {.lex_state = 5},
  [34] = {.lex_state = 9},
  [35] = {.lex_state = 3},
  [36] = {.lex_state = 5},
  [37] = {.lex_state = 9},
  [38] = {.lex_state = 9},
  [39] = {.lex_state = 3},
  [40] = {.lex_state = 5},
  [41] = {.lex_state = 5},
  [42] = {.lex_state = 9},
  [43] = {.lex_state = 5},
  [44] = {.lex_state = 5},
  [45] = {.lex_state = 5},
  [46] = {.lex_state = 9},
  [47] = {.lex_state = 8},
  [48] = {.lex_state = 6},
  [49] = {.lex_state = 8},
  [50] = {.lex_state = 6},
  [51] = {.lex_state = 0},
  [52] = {.lex_state = 6},
  [53] = {.lex_state = 8},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_name_section] = ACTIONS(1),
    [sym_stop_section] = ACTIONS(1),
    [sym_comment] = ACTIONS(1),
    [sym_tag] = ACTIONS(1),
    [aux_sym_narrative_token1] = ACTIONS(1),
    [anon_sym_u2014] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(51),
    [sym_section] = STATE(6),
    [sym_tag_line] = STATE(6),
    [sym_narrative] = STATE(6),
    [sym_dialog] = STATE(6),
    [sym__open_dialog] = STATE(38),
    [sym__end_dialog] = STATE(24),
    [aux_sym_document_repeat1] = STATE(6),
    [aux_sym_dialog_repeat1] = STATE(28),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_name_section] = ACTIONS(5),
    [sym_comment] = ACTIONS(7),
    [sym_tag] = ACTIONS(9),
    [aux_sym_narrative_token1] = ACTIONS(11),
    [anon_sym_u2014] = ACTIONS(13),
  },
  [STATE(2)] = {
    [sym_tag_line] = STATE(5),
    [sym_narrative] = STATE(5),
    [sym_dialog] = STATE(5),
    [sym__open_dialog] = STATE(37),
    [sym__end_dialog] = STATE(8),
    [aux_sym_section_repeat1] = STATE(5),
    [aux_sym_dialog_repeat1] = STATE(27),
    [ts_builtin_sym_end] = ACTIONS(15),
    [sym_name_section] = ACTIONS(17),
    [sym_stop_section] = ACTIONS(19),
    [sym_comment] = ACTIONS(21),
    [sym_tag] = ACTIONS(23),
    [aux_sym_narrative_token1] = ACTIONS(25),
    [anon_sym_u2014] = ACTIONS(27),
  },
  [STATE(3)] = {
    [sym_tag_line] = STATE(3),
    [sym_narrative] = STATE(3),
    [sym_dialog] = STATE(3),
    [sym__open_dialog] = STATE(37),
    [sym__end_dialog] = STATE(8),
    [aux_sym_section_repeat1] = STATE(3),
    [aux_sym_dialog_repeat1] = STATE(27),
    [ts_builtin_sym_end] = ACTIONS(29),
    [sym_name_section] = ACTIONS(31),
    [sym_stop_section] = ACTIONS(31),
    [sym_comment] = ACTIONS(33),
    [sym_tag] = ACTIONS(36),
    [aux_sym_narrative_token1] = ACTIONS(39),
    [anon_sym_u2014] = ACTIONS(42),
  },
  [STATE(4)] = {
    [sym_section] = STATE(4),
    [sym_tag_line] = STATE(4),
    [sym_narrative] = STATE(4),
    [sym_dialog] = STATE(4),
    [sym__open_dialog] = STATE(38),
    [sym__end_dialog] = STATE(24),
    [aux_sym_document_repeat1] = STATE(4),
    [aux_sym_dialog_repeat1] = STATE(28),
    [ts_builtin_sym_end] = ACTIONS(45),
    [sym_name_section] = ACTIONS(47),
    [sym_comment] = ACTIONS(50),
    [sym_tag] = ACTIONS(53),
    [aux_sym_narrative_token1] = ACTIONS(56),
    [anon_sym_u2014] = ACTIONS(59),
  },
  [STATE(5)] = {
    [sym_tag_line] = STATE(3),
    [sym_narrative] = STATE(3),
    [sym_dialog] = STATE(3),
    [sym__open_dialog] = STATE(37),
    [sym__end_dialog] = STATE(8),
    [aux_sym_section_repeat1] = STATE(3),
    [aux_sym_dialog_repeat1] = STATE(27),
    [ts_builtin_sym_end] = ACTIONS(62),
    [sym_name_section] = ACTIONS(64),
    [sym_stop_section] = ACTIONS(66),
    [sym_comment] = ACTIONS(68),
    [sym_tag] = ACTIONS(23),
    [aux_sym_narrative_token1] = ACTIONS(25),
    [anon_sym_u2014] = ACTIONS(27),
  },
  [STATE(6)] = {
    [sym_section] = STATE(4),
    [sym_tag_line] = STATE(4),
    [sym_narrative] = STATE(4),
    [sym_dialog] = STATE(4),
    [sym__open_dialog] = STATE(38),
    [sym__end_dialog] = STATE(24),
    [aux_sym_document_repeat1] = STATE(4),
    [aux_sym_dialog_repeat1] = STATE(28),
    [ts_builtin_sym_end] = ACTIONS(70),
    [sym_name_section] = ACTIONS(5),
    [sym_comment] = ACTIONS(72),
    [sym_tag] = ACTIONS(9),
    [aux_sym_narrative_token1] = ACTIONS(11),
    [anon_sym_u2014] = ACTIONS(13),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 6,
    ACTIONS(13), 1,
      anon_sym_u2014,
    ACTIONS(74), 1,
      aux_sym_narrative_token1,
    STATE(24), 1,
      sym__end_dialog,
    STATE(28), 1,
      aux_sym_dialog_repeat1,
    STATE(38), 1,
      sym__open_dialog,
    STATE(17), 2,
      sym_narrative,
      sym_dialog,
  [20] = 2,
    ACTIONS(76), 1,
      ts_builtin_sym_end,
    ACTIONS(78), 6,
      sym_name_section,
      sym_stop_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [32] = 2,
    ACTIONS(80), 1,
      ts_builtin_sym_end,
    ACTIONS(82), 6,
      sym_name_section,
      sym_stop_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [44] = 2,
    ACTIONS(84), 1,
      ts_builtin_sym_end,
    ACTIONS(86), 6,
      sym_name_section,
      sym_stop_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [56] = 2,
    ACTIONS(88), 1,
      ts_builtin_sym_end,
    ACTIONS(90), 6,
      sym_name_section,
      sym_stop_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [68] = 2,
    ACTIONS(92), 1,
      ts_builtin_sym_end,
    ACTIONS(94), 6,
      sym_name_section,
      sym_stop_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [80] = 2,
    ACTIONS(96), 1,
      ts_builtin_sym_end,
    ACTIONS(98), 6,
      sym_name_section,
      sym_stop_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [92] = 2,
    ACTIONS(100), 1,
      ts_builtin_sym_end,
    ACTIONS(102), 6,
      sym_name_section,
      sym_stop_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [104] = 2,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
    ACTIONS(106), 6,
      sym_name_section,
      sym_stop_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [116] = 6,
    ACTIONS(27), 1,
      anon_sym_u2014,
    ACTIONS(108), 1,
      aux_sym_narrative_token1,
    STATE(8), 1,
      sym__end_dialog,
    STATE(27), 1,
      aux_sym_dialog_repeat1,
    STATE(37), 1,
      sym__open_dialog,
    STATE(11), 2,
      sym_narrative,
      sym_dialog,
  [136] = 2,
    ACTIONS(88), 1,
      ts_builtin_sym_end,
    ACTIONS(90), 5,
      sym_name_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [147] = 2,
    ACTIONS(96), 1,
      ts_builtin_sym_end,
    ACTIONS(98), 5,
      sym_name_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [158] = 2,
    ACTIONS(62), 1,
      ts_builtin_sym_end,
    ACTIONS(64), 5,
      sym_name_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [169] = 2,
    ACTIONS(92), 1,
      ts_builtin_sym_end,
    ACTIONS(94), 5,
      sym_name_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [180] = 2,
    ACTIONS(110), 1,
      ts_builtin_sym_end,
    ACTIONS(112), 5,
      sym_name_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [191] = 2,
    ACTIONS(100), 1,
      ts_builtin_sym_end,
    ACTIONS(102), 5,
      sym_name_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [202] = 2,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
    ACTIONS(106), 5,
      sym_name_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [213] = 2,
    ACTIONS(76), 1,
      ts_builtin_sym_end,
    ACTIONS(78), 5,
      sym_name_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [224] = 2,
    ACTIONS(80), 1,
      ts_builtin_sym_end,
    ACTIONS(82), 5,
      sym_name_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [235] = 2,
    ACTIONS(84), 1,
      ts_builtin_sym_end,
    ACTIONS(86), 5,
      sym_name_section,
      sym_comment,
      sym_tag,
      aux_sym_narrative_token1,
      anon_sym_u2014,
  [246] = 4,
    ACTIONS(114), 1,
      anon_sym_u2014,
    STATE(10), 1,
      sym__end_dialog,
    STATE(30), 1,
      aux_sym_dialog_repeat1,
    STATE(34), 1,
      sym__open_dialog,
  [259] = 4,
    ACTIONS(116), 1,
      anon_sym_u2014,
    STATE(26), 1,
      sym__end_dialog,
    STATE(30), 1,
      aux_sym_dialog_repeat1,
    STATE(31), 1,
      sym__open_dialog,
  [272] = 3,
    ACTIONS(118), 1,
      anon_sym_u2014,
    ACTIONS(120), 1,
      anon_sym_LF,
    STATE(18), 1,
      sym__eol,
  [282] = 3,
    ACTIONS(122), 1,
      anon_sym_u2014,
    STATE(30), 1,
      aux_sym_dialog_repeat1,
    STATE(42), 1,
      sym__open_dialog,
  [292] = 3,
    ACTIONS(125), 1,
      aux_sym__open_narrative_token1,
    STATE(23), 1,
      sym__end_narrative,
    STATE(53), 1,
      sym__open_narrative,
  [302] = 3,
    ACTIONS(118), 1,
      anon_sym_u2014,
    ACTIONS(127), 1,
      anon_sym_LF,
    STATE(13), 1,
      sym__eol,
  [312] = 3,
    ACTIONS(129), 1,
      anon_sym_u2014,
    ACTIONS(131), 1,
      anon_sym_LF,
    STATE(14), 1,
      sym__eol,
  [322] = 3,
    ACTIONS(133), 1,
      aux_sym__open_narrative_token1,
    STATE(15), 1,
      sym__end_narrative,
    STATE(53), 1,
      sym__open_narrative,
  [332] = 3,
    ACTIONS(135), 1,
      aux_sym_narrative_token2,
    ACTIONS(137), 1,
      anon_sym_LF,
    STATE(25), 1,
      sym__eol,
  [342] = 3,
    ACTIONS(129), 1,
      anon_sym_u2014,
    ACTIONS(139), 1,
      anon_sym_LF,
    STATE(22), 1,
      sym__eol,
  [352] = 3,
    ACTIONS(133), 1,
      aux_sym__open_narrative_token1,
    STATE(10), 1,
      sym__end_narrative,
    STATE(53), 1,
      sym__open_narrative,
  [362] = 3,
    ACTIONS(125), 1,
      aux_sym__open_narrative_token1,
    STATE(26), 1,
      sym__end_narrative,
    STATE(53), 1,
      sym__open_narrative,
  [372] = 3,
    ACTIONS(141), 1,
      aux_sym_narrative_token2,
    ACTIONS(143), 1,
      anon_sym_LF,
    STATE(9), 1,
      sym__eol,
  [382] = 2,
    ACTIONS(145), 1,
      anon_sym_LF,
    STATE(12), 1,
      sym__eol,
  [389] = 2,
    ACTIONS(147), 1,
      anon_sym_LF,
    STATE(2), 1,
      sym__eol,
  [396] = 2,
    ACTIONS(149), 1,
      aux_sym__open_narrative_token1,
    STATE(53), 1,
      sym__open_narrative,
  [403] = 2,
    ACTIONS(151), 1,
      anon_sym_LF,
    STATE(7), 1,
      sym__eol,
  [410] = 2,
    ACTIONS(153), 1,
      anon_sym_LF,
    STATE(20), 1,
      sym__eol,
  [417] = 2,
    ACTIONS(155), 1,
      anon_sym_LF,
    STATE(16), 1,
      sym__eol,
  [424] = 1,
    ACTIONS(157), 1,
      aux_sym__open_narrative_token1,
  [428] = 1,
    ACTIONS(159), 1,
      anon_sym_u2014,
  [432] = 1,
    ACTIONS(161), 1,
      aux_sym__open_dialog_token1,
  [436] = 1,
    ACTIONS(163), 1,
      anon_sym_u2014,
  [440] = 1,
    ACTIONS(165), 1,
      aux_sym__open_dialog_token1,
  [444] = 1,
    ACTIONS(167), 1,
      ts_builtin_sym_end,
  [448] = 1,
    ACTIONS(169), 1,
      aux_sym__open_dialog_token1,
  [452] = 1,
    ACTIONS(171), 1,
      anon_sym_u2014,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(7)] = 0,
  [SMALL_STATE(8)] = 20,
  [SMALL_STATE(9)] = 32,
  [SMALL_STATE(10)] = 44,
  [SMALL_STATE(11)] = 56,
  [SMALL_STATE(12)] = 68,
  [SMALL_STATE(13)] = 80,
  [SMALL_STATE(14)] = 92,
  [SMALL_STATE(15)] = 104,
  [SMALL_STATE(16)] = 116,
  [SMALL_STATE(17)] = 136,
  [SMALL_STATE(18)] = 147,
  [SMALL_STATE(19)] = 158,
  [SMALL_STATE(20)] = 169,
  [SMALL_STATE(21)] = 180,
  [SMALL_STATE(22)] = 191,
  [SMALL_STATE(23)] = 202,
  [SMALL_STATE(24)] = 213,
  [SMALL_STATE(25)] = 224,
  [SMALL_STATE(26)] = 235,
  [SMALL_STATE(27)] = 246,
  [SMALL_STATE(28)] = 259,
  [SMALL_STATE(29)] = 272,
  [SMALL_STATE(30)] = 282,
  [SMALL_STATE(31)] = 292,
  [SMALL_STATE(32)] = 302,
  [SMALL_STATE(33)] = 312,
  [SMALL_STATE(34)] = 322,
  [SMALL_STATE(35)] = 332,
  [SMALL_STATE(36)] = 342,
  [SMALL_STATE(37)] = 352,
  [SMALL_STATE(38)] = 362,
  [SMALL_STATE(39)] = 372,
  [SMALL_STATE(40)] = 382,
  [SMALL_STATE(41)] = 389,
  [SMALL_STATE(42)] = 396,
  [SMALL_STATE(43)] = 403,
  [SMALL_STATE(44)] = 410,
  [SMALL_STATE(45)] = 417,
  [SMALL_STATE(46)] = 424,
  [SMALL_STATE(47)] = 428,
  [SMALL_STATE(48)] = 432,
  [SMALL_STATE(49)] = 436,
  [SMALL_STATE(50)] = 440,
  [SMALL_STATE(51)] = 444,
  [SMALL_STATE(52)] = 448,
  [SMALL_STATE(53)] = 452,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [7] = {.entry = {.count = 1, .reusable = false}}, SHIFT(6),
  [9] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(35),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [15] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 2, 0, 0),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 2, 0, 0),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(5),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [25] = {.entry = {.count = 1, .reusable = false}}, SHIFT(39),
  [27] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [29] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0),
  [33] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [36] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(45),
  [39] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(39),
  [42] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_section_repeat1, 2, 0, 0), SHIFT_REPEAT(50),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [47] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(41),
  [50] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(4),
  [53] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(43),
  [56] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(35),
  [59] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(48),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 3, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 3, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(3),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dialog, 1, 0, 0),
  [78] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dialog, 1, 0, 0),
  [80] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_narrative, 2, 0, 0),
  [82] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_narrative, 2, 0, 0),
  [84] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dialog, 2, 0, 0),
  [86] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dialog, 2, 0, 0),
  [88] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_tag_line, 3, 0, 0),
  [90] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_tag_line, 3, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_narrative, 3, 0, 0),
  [94] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_narrative, 3, 0, 0),
  [96] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__end_dialog, 3, 0, 0),
  [98] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__end_dialog, 3, 0, 0),
  [100] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__end_narrative, 2, 0, 0),
  [102] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__end_narrative, 2, 0, 0),
  [104] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_dialog, 3, 0, 0),
  [106] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_dialog, 3, 0, 0),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [110] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_section, 4, 0, 0),
  [112] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_section, 4, 0, 0),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [118] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [120] = {.entry = {.count = 1, .reusable = true}}, SHIFT(18),
  [122] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_dialog_repeat1, 2, 0, 0), SHIFT_REPEAT(52),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [129] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__open_narrative, 1, 0, 0),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [133] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [135] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [137] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [139] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [141] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [143] = {.entry = {.count = 1, .reusable = false}}, SHIFT(9),
  [145] = {.entry = {.count = 1, .reusable = true}}, SHIFT(12),
  [147] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [149] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [151] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [153] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [155] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [157] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__open_dialog, 3, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__open_narrative, 1, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [163] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [165] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [167] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [169] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_dialog_repeat1, 2, 0, 0),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_draft(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .primary_state_ids = ts_primary_state_ids,
    .name = "draft",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
